import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DWV',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const nonce = 'abc123'; // Defina o valor do atributo nonce aqui

  return (
    <html lang="pt">
      <Head>
        <meta httpEquiv="Content-Security-Policy" content={`default-src 'self'; script-src 'self' 'nonce-${nonce}';`} />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
